
name: 'Install and cache Node modules' # имя экшена
description: 'Some Description'   # описание экшена


runs: # указываем тип экшена
  using: 'composite'
  steps:
    - name: Cache node_modules
      id: cache-step
      uses: actions/cache@v3
      with:
        path: ~/.npm

        key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }} # лучше генерировать динамический ключ
        restore-keys: | # будет искаться если другой не найдётся
          ${{ runner.os }}-cache-file-
          ${{ runner.os }}-
    - name: Display Cache # отображаем кэш по его id
      run: echo '${{ tojson(steps.cache-step.outputs) }}'
      shell: bash   # для каждого  run тут надо указать bash
    - name: Install node_modules # устанавливаем зависимости
      run: npm install
      shell: bash
