name: Seventh Workflow
#on: [push, issues, pull_request] # список иветнов для запуска

on:
  schedule:
    - cron: "*/5 * * * *" # мин/час/день/мес/ден нед

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name:
        run:
          echo "schedule ASD"
          echo $GITHUB_REF
