name: First Workflow
on: [push] #  квадратные скобки нужны,если запускаются несколько ивентов

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Asd
        run: echo "Some text"
      - name: Display new Qwerty
        run: |
          node -v
          npm -v
