name: Six Workflow
#on: [push, issues, pull_request] # список иветнов для запуска

on:
  push:
    branches: # запускаем если пуш через ветку main
      - main
      - "page/*" # для запуска всех из директории(слэш звездочка не видит(/**))
      - "!page/blog" # кроме этой ветки
    #branches-ignore: # использовать только в отсутствии фильтра 'branches'
    # - "игнорируемая ветка"
    paths: # запускаем только если изменения произошли в указанной папке
      - "**.html"
      #патерны см док. Тут фильтр пропустит все html
    tags:
      - "v1*" # фильтр для запуска только нужной версии. * в роли патерна для v1.1, v1.1.2  и т.п.
      - "!v1.2.3" # чтобы исключить нужную версию


jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event vars
        run:
          echo "Asd test"
          echo $GITHUB_SHA
          echo $GITHUB_REF