name: Second Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: | # смотрим что лежит в каталоге
          ls -a
      #- uses: actions/checkout@v4 # копируем репозиторий чекаутом
      - name: Copy Files
        run: | # если список команд, то используем этот символ ( | )
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: New List Files
        run:
          ls -a
