name: Second Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files and Copy Repo
        run: | # копируем репозиторий чекаутом и смотрим что лежит в каталоге
          ls -a
      - uses: actions/checkout@v4
      - name: New List Files
        run:
          ls -a
