# изучаем функции failure(), success(), always(), cancelled()

name: Thirteenth Workflow
on: [push]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: # установим тайм-аут
          #sleep 30
          exit 1
      - name: Runs on Canceled # здесь canceled вернёт True, если предидущие шаги были отменены, в иных случаях этот run пропустится
        if: ${{ cancelled() }}
        run: echo "Runs on canceled"

      - name: Runs on any case # always запустится в любом случае
        if: ${{ always() }}
        run: echo "Runs on any case"

      - name: Runs on Success #
        if: ${{ success() }}
        run: echo "Runs on Success"

      - name: Runs on Failure # этот шаг запустится, если где то ранее произойдет ошибка
        if: ${{ failure() }}
        run: echo "Runs on Failure"

  second_job:
    runs-on: ubuntu-latest

    needs: job # ставим зависимость от первого job
    if: ${{ failure() }} # если он провалится
    steps:
      - run: echo "Job was failed"

