name: Twelwe Workflow
on: [push] # список иветнов для запуска

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "production"

    steps:
      - name: Our Vars & Secrets
        run: | #  достаём переменные из секрет, варс 
          echo ${{ vars.STATUS }}
          echo ${{ secrets.MY_PASSWORD }}
