
name: Then Workflow

on: workflow_dispatch
run-name: "Display Context info" # задаем кастомный заголовок если хотим

jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title
        run: echo 'test Asd'
      - uses: actions/checkout@v4
      - name: set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
         
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: new Title
        run: echo 'new Asd'
        
      - name: Run mypy  #проверяем код линтером
        run: |
          mypy main1.py
