# ограничение количества одновременных запусков workflow

name: Concorrency testing
on: workflow_dispatch
#concurrency: concurrency-testing-id # разрешает запускать только один воркфлоу и один ставит в ожидание,остальные отменяются

concurrency:    # при таком concurrency при нескольких запусках будет работать последний запущенный
  group: conc_test_id
  cancel_in_progress: true

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Some Step
        run: sleep 35
        timeout-minutes: 1   # ставим таймер работы для workflow на уровне шага
