# работа с артефактами. сохранение ф файл, загрузка,изменение
name: Fifteenth Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt
      - name: Upload resalt file
        uses: actions/upload-artifact@v7 # загружаем в файл
        with:
          name: math-result
          path: math-result.txt
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download file
        uses: actions/download-artifact@v7 # загружаем файл
        with:
          name: math-result
      - name: Print File
        run: |
          value=`cat math-result.txt`
          echo $value