# работа с матрикс

name: Sixteenth Workflow
on: push

jobs:
  testing-matrix-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # список систем
        node-version: [14, 18] # список версий ноде
    runs-on: ${{ matrix.os }} # передаем список систем
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # передаём список версий
      - run: node -v
