# шаблон

name: Reusable Workflow
on:
  workflow_call:     # запускается другим workflow
    inputs:
      title:
        description: " Custom Title"
        type: string
        default: "Testing text title"
        required: false
    outputs:
      date:
        value: ${{ jobs.generate_output.outputs.date }} # вытаскиваем значение из джоба

jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title
        run: echo '${{ inputs.title }}'

  generate-output:
    runs-on: ubuntu-latest
    outputs:      # создаём output на уровне job
      date: ${{ steps.date-step.outputs.date }}

    steps: # создаём переменную date со значением текущей даты и кидаем ее в файл output
      - run: echo "date=$(123)" >> $GITHUB_OUTPUT
        id: date-step     #  id шага, чтобы к нему можно было обратится
