# работа с матрикс

name: Sixteenth Workflow
on: push

jobs:
  testing-matrix-job:
    continue-on-error: true                    # чтобы завершение джоба было успешным, даже если один из джобов вернёт неудачу
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]    # список систем
        node-version: [12, 14, 18]             # список версий ноде. Если 12 упадёт, остальные не запустятся

        include:                               # добавить в загрузку
          - os: macos-latest
            node-version: 17
        exclude:                               # убрать из загрузки
          - os: ubuntu-latest
            node-version: 14

      fail-fast: false                         # чтобы продолжить цепочку запусков, если вдруг один из джобов упадёт

      max-parallel: 2                          # ограничить количество паралельных запусков джобов

    runs-on: ${{ matrix.os }}                  # передаем список систем
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}    # передаём список версий
      - run: node -v
