# работа с docker

name: Docker Test
on: push

jobs:
  test-docker-container:    # открываем другой из этого репозитория
    runs-on: ubuntu-latest
    services:     # тут можно задать сервисы докера. например Mysql
      customMysql:
        image: mysql
    container:           #  Создаём контейнер на уровне джжоба
      image: node:21-alpine3.17 # задаём версию node и операционки (os)
      env:
        NODE_ENV: development   #  введем какую нибудь переменную
      ports:
        - 80

    steps:           #  шаги относятся уже к node
      - name: Display service image
        run:        # посмотрим на подключенный в джобе сервис
          echo '${{ toJSON(job.services) }}'

      - name: Display Node version
        run: |
          node -v
          cat /etc/os-release

      - name: print new Node version  # можем создать контейнер и на уровне шага
        uses: docker://node:18-buster-slim  # укажем,какую хоитм версию
        with:
          args: -v  # посмотрим версию
