# установка таймера, чтобы workflow не зацикливался

name: Twentieth Workflow(test timeout)
on: push

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    #timeout-minutes: 1   # ставим таймер работы для workflow на уровне джоба
    steps:
      - name: Some Step
        run: sleep 25
        timeout-minutes: 1   # ставим таймер работы для workflow на уровне шага
